// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	parking "github.com/Lucifer07/parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// UpdateAvailable provides a mock function with given fields: _a0
func (_m *Observer) UpdateAvailable(_a0 *parking.ParkingLot) {
	_m.Called(_a0)
}

// UpdateFull provides a mock function with given fields: _a0
func (_m *Observer) UpdateFull(_a0 *parking.ParkingLot) {
	_m.Called(_a0)
}
