// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	parking "github.com/Lucifer07/parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// StyleContract is an autogenerated mock type for the StyleContract type
type StyleContract struct {
	mock.Mock
}

// GetParkingLot provides a mock function with given fields: lots
func (_m *StyleContract) GetParkingLot(lots []*parking.ParkingLot) *parking.ParkingLot {
	ret := _m.Called(lots)

	var r0 *parking.ParkingLot
	if rf, ok := ret.Get(0).(func([]*parking.ParkingLot) *parking.ParkingLot); ok {
		r0 = rf(lots)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parking.ParkingLot)
		}
	}

	return r0
}
